fullnameOverride: ghcr-proxy

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

configuration:
  proxy:
    remoteurl: https://ghcr.io
