{{- $name := include "hetzner-cluster.name" . }}
{{- $controlPlaneName := include "hetzner-cluster.controlPlaneName" . }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "hetzner-cluster.labels" . | nindent 4 }}
spec:
  clusterNetwork: {{ .Values.cluster.clusterNetwork | toYaml | nindent 4 }}
  controlPlaneEndpoint: {{ .Values.cluster.controlPlaneEndpoint | toYaml | nindent 4 }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: {{ $name | quote }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: {{ $controlPlaneName | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "hetzner-cluster.labels" . | nindent 4 }}
spec:
  hcloudNetwork:
    enabled: false
  controlPlaneRegions: {{ .Values.controlPlane.regions | toYaml | nindent 4 }}
  controlPlaneEndpoint: {{ .Values.cluster.controlPlaneEndpoint | toYaml | nindent 4 }}
  controlPlaneLoadBalancer:
    enabled: {{ .Values.controlPlane.loadBalancer.enabled }}
    region: {{ .Values.controlPlane.loadBalancer.region | quote }}
    type: {{ .Values.controlPlane.loadBalancer.type | quote }}
  sshKeys:
    hcloud:
      - name: {{ .Values.cluster.sshKeyName | quote }}
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    {{- range $index, $machineDeployment := .Values.machineDeployments }}
    - name: {{ printf "md-%d" $index | quote }}
      type: spread
    {{- end }}
  hetznerSecretRef:
    name: hcloud
    key:
      hcloudToken: token
