{{- $name := include "hetzner-cluster.name" . }}
{{- $labels := include "hetzner-cluster.labels" . }}
{{- $selectorLabels := include "hetzner-cluster.selectorLabels" . }}
{{- range $index, $machineDeployment := .Values.machineDeployments }}
{{- $machineDeploymentName := printf "%s-md-%d" $.Release.Name $index | trunc 63 | trimSuffix "-" }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $machineDeploymentName | quote }}
  labels:
    {{- $labels | nindent 4 }}
    cluster.x-k8s.io/deployment-name: {{ $machineDeploymentName | quote }}
spec:
  clusterName: {{ $name | quote }}
  replicas: {{ $machineDeployment.replicas }}
  template:
    metadata:
      labels:
        {{- $labels | nindent 8 }}
        cluster.x-k8s.io/deployment-name: {{ $machineDeploymentName | quote }}
    spec:
      clusterName: {{ $name | quote }}
      failureDomain: {{ $machineDeployment.region | quote }}
      version: {{ $.Values.cluster.kubernetesVersion | quote }}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $machineDeploymentName | quote }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ $machineDeploymentName | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ $machineDeploymentName | quote }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  template:
    spec:
      type: {{ $machineDeployment.type | quote }}
      imageName: {{ $machineDeployment.image | quote }}
      placementGroupName: {{ printf "md-%d" $index | quote }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ $machineDeploymentName | quote }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  template:
    spec:
      joinConfiguration: {{ $machineDeployment.joinConfiguration | toYaml | nindent 8 }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ $machineDeploymentName | quote }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  clusterName: {{ $name | quote }}
  maxUnhealthy: 100%
  nodeStartupTimeout: 10m
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      cluster.x-k8s.io/deployment-name: {{ $machineDeploymentName | quote }}
  unhealthyConditions:
    - type: Ready
      status: Unknown
      timeout: 180s
    - type: Ready
      status: "False"
      timeout: 180s
  remediationTemplate:
    kind: HCloudRemediationTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    name: {{ $machineDeploymentName | quote }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudRemediationTemplate
metadata:
  name: {{ $machineDeploymentName | quote }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  template:
    spec:
      strategy:
        type: Reboot
        retryLimit: 1
        timeout: 180s
{{- end }}
