apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registry.fullname" . }}-config
  labels:
    {{- include "registry.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.configuration | nindent 4 }}
